[project]
name = "voice-input"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "evdev>=1.9.1",
    "faster-whisper>=1.1.1",
    "scipy>=1.15.2",
    "sounddevice>=0.5.1",
]

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
